### ISSUE TITLE
Search module index data makes JSON output invalid

### ISSUE THREAD

**Issue by bkoopman** [sdl/dxa-modules#26]
See https://github.com/SI4T/SI4T/issues/4 for original issue, since the DXA Search module is using SI4T for the search indexing, we will need to fix this in SI4T via a Pull Request.

**Comment by rpannekoek** [comment]
This is just the way how SI4T (currently) works.  It adds an XML comment preface to the JSON output, resulting in a weird combination of XML and JSON, but the XML comment is removed in the deployer extension, so the published data stored in the CD Data Store is regular, valid JSON.

The intermediate XML/JSON mix is quirky, but there is not a real issue.

There are plans to introduce built-in Search functionality in Tridion Sites 9.1, so a subsequent DXA release can leverage this functionality instead of SI4T-based search.  Therefore, it is not attractive to invest in improving the SI4T-based search.
